name:                doldol
version:             0.4.2.0
homepage:            http://dev.quietjoon.net/projects/doldol.html
github:              "QuietJoon/doldol"
license:             BSD3
category:            Data
author:              "YongJoon Joe"
maintainer:          "developer+doldol@quietjoon.net"
copyright:           2017-2019 YongJoon Joe

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Flag packer & handler for flaggable data
description:         Please see the README on GitHub at <https://github.com/QuietJoon/doldol#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq

library:
  source-dirs: src
  other-modules: []

tests:
  doldol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - doldol
    - HUnit
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
